version: "3.9"
services:
  web:
    build: ""
    ports:
      - "8000:8000"
    command: bash -c "python manage.py makemigrations app &&
                      python manage.py migrate app &&
                      python manage.py load_data &&
                      python manage.py runserver 0.0.0.0:8000"
